const path = require('path');
const crypto = require('crypto');
const multer = require('multer');
const { Ticket, TicketType, TicketPanel, Transcript, AuditLog, StaffMember, GuildSettings, BotProfile, Guild, User } = require('../database/models');
const { dashboardUrl, clientId, clientSecret, redirectUri } = require('../config/env');
const { canManageGuild } = require('../bot/utils/permissions');

const upload = multer({ storage:multer.memoryStorage(), limits:{fileSize:5*1024*1024}, fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpeg|webp|gif)$/.test(file.mimetype)) });
const DISCORD_API='https://discord.com/api/v10';
function auth(req,res,next){ if(!req.session.user) return res.status(401).json({error:'Not authenticated'}); next(); }
function csrf(req,res,next){ if(['GET','HEAD','OPTIONS'].includes(req.method)) return next(); if(!req.session.csrf || req.get('x-csrf-token')!==req.session.csrf) return res.status(403).json({error:'Invalid CSRF token'}); next(); }
async function discordFetch(url, options={}) { const r=await fetch(`${DISCORD_API}${url}`,options); const data=await r.json().catch(()=>({})); if(!r.ok) throw new Error(data.message||`Discord API ${r.status}`); return data; }
async function getGuilds(req){ const gs=await discordFetch('/users/@me/guilds',{headers:{Authorization:`Bearer ${req.session.user.accessToken}`}}); return gs.filter(g => (Number(g.permissions)&0x20)===0x20 || (Number(g.permissions)&0x8)===0x8); }
async function ensureGuildAccess(req,guildId){ const gs=await getGuilds(req); if(!gs.some(g=>g.id===guildId)) throw new Error('You do not have permission to manage this server.'); return gs.find(g=>g.id===guildId); }
function bodyFields(req, fields){ const out={}; for(const f of fields) if(req.body[f]!==undefined) out[f]=req.body[f]; return out; }
function json(res,data,status=200){ return res.status(status).json(data); }
function startDashboard(app, client){
  app.get('/auth/discord', (req,res)=>{ req.session.oauthState=crypto.randomBytes(16).toString('hex'); const u=new URL('https://discord.com/oauth2/authorize'); u.searchParams.set('client_id',clientId); u.searchParams.set('response_type','code'); u.searchParams.set('redirect_uri',redirectUri); u.searchParams.set('scope','identify guilds'); u.searchParams.set('state',req.session.oauthState); res.redirect(u.toString()); });
  app.get('/auth/discord/callback', async (req,res)=>{ try { if(!req.query.code || req.query.state!==req.session.oauthState) return res.status(400).send('Invalid OAuth state.'); const token=await discordFetch('/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:clientId,client_secret:clientSecret,grant_type:'authorization_code',code:req.query.code,redirect_uri:redirectUri})}); const me=await discordFetch('/users/@me',{headers:{Authorization:`Bearer ${token.access_token}`}}); req.session.user={id:me.id,username:me.global_name||me.username,avatar:me.avatar,accessToken:token.access_token}; req.session.csrf=crypto.randomBytes(24).toString('hex'); await User.findOneAndUpdate({userId:me.id},{userId:me.id,username:me.global_name||me.username,avatar:me.avatar},{upsert:true}); res.redirect('/dashboard/'); } catch(e){ res.status(500).send(`OAuth failed: ${e.message}`); } });
  app.get('/auth/logout',(req,res)=>req.session.destroy(()=>res.redirect('/dashboard/')));
  app.get('/api/auth/me',(req,res)=>json(res,{authenticated:Boolean(req.session.user),user:req.session.user?{id:req.session.user.id,username:req.session.user.username,avatar:req.session.user.avatar}:null,csrf:req.session.csrf||null}));
  app.use('/api',csrf);
  app.get('/api/guilds',auth,async(req,res)=>{ try{ const gs=await getGuilds(req); const out=gs.map(g=>({id:g.id,name:g.name,icon:g.icon,botPresent:Boolean(client.guilds.cache.get(g.id))})); return json(res,out); }catch(e){return json(res,{error:e.message},500)} });
  app.get('/api/guilds/:guildId',auth,async(req,res)=>{ try{ const g=await ensureGuildAccess(req,req.params.guildId); const settings=await GuildSettings.findOne({guildId:g.id})||{}; const profile=await BotProfile.findOne({guildId:g.id})||{}; const [open,closed,today,month,types,panels,transcripts]=await Promise.all([Ticket.countDocuments({guildId:g.id,status:'open'}),Ticket.countDocuments({guildId:g.id,status:'closed'}),Ticket.countDocuments({guildId:g.id,createdAt:{$gte:new Date(Date.now()-86400000)}}),Ticket.countDocuments({guildId:g.id,createdAt:{$gte:new Date(new Date().getFullYear(),new Date().getMonth(),1)}}),TicketType.countDocuments({guildId:g.id}),TicketPanel.countDocuments({guildId:g.id}),Transcript.countDocuments({guildId:g.id})]); return json(res,{guild:g,settings,profile,stats:{open,closed,today,month,types,panels,transcripts}}); }catch(e){return json(res,{error:e.message},403)} });
  app.get('/api/guilds/:guildId/settings',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);return json(res,await GuildSettings.findOneAndUpdate({guildId:req.params.guildId},{$setOnInsert:{guildId:req.params.guildId}},{upsert:true,new:true}));}catch(e){return json(res,{error:e.message},403)}});
  app.put('/api/guilds/:guildId/settings',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);const data=bodyFields(req,['transcriptChannelId','ticketLogChannelId','staffLogChannelId','defaultCategoryId','dashboardEnabled','transcriptVisibility','ticketCooldownSeconds','maxOpenTicketsPerUser','autoCloseEnabled','claimRequired','dmTranscript','permissions','branding']);const s=await GuildSettings.findOneAndUpdate({guildId:req.params.guildId},{$set:data,$setOnInsert:{guildId:req.params.guildId}},{upsert:true,new:true});return json(res,s)}catch(e){return json(res,{error:e.message},400)}});
  app.get('/api/guilds/:guildId/ticket-types',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);return json(res,await TicketType.find({guildId:req.params.guildId}).sort({createdAt:-1}))}catch(e){return json(res,{error:e.message},403)}});
  app.post('/api/guilds/:guildId/ticket-types',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);const t=await TicketType.create({guildId:req.params.guildId,...bodyFields(req,['name','description','buttonLabel','buttonStyle','categoryId','supportRoleIds','namingFormat','welcomeMessage','autoClose','transcriptEnabled','logEnabled','permissionOverrides','enabled'])});return json(res,t,201)}catch(e){return json(res,{error:e.message},400)}});
  app.put('/api/guilds/:guildId/ticket-types/:id',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);const t=await TicketType.findOneAndUpdate({_id:req.params.id,guildId:req.params.guildId},{$set:req.body},{new:true});if(!t)return json(res,{error:'Ticket type not found'},404);return json(res,t)}catch(e){return json(res,{error:e.message},400)}});
  app.delete('/api/guilds/:guildId/ticket-types/:id',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);await TicketType.deleteOne({_id:req.params.id,guildId:req.params.guildId});return json(res,{ok:true})}catch(e){return json(res,{error:e.message},400)}});
  app.get('/api/guilds/:guildId/panels',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);return json(res,await TicketPanel.find({guildId:req.params.guildId}).sort({createdAt:-1}))}catch(e){return json(res,{error:e.message},403)}});
  app.post('/api/guilds/:guildId/panels',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);const p=await TicketPanel.create({guildId:req.params.guildId,...bodyFields(req,['name','channelId','title','description','image','thumbnail','banner','color','ticketTypeIds','buttons','published'])});return json(res,p,201)}catch(e){return json(res,{error:e.message},400)}});
  app.put('/api/guilds/:guildId/panels/:id',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);const p=await TicketPanel.findOneAndUpdate({_id:req.params.id,guildId:req.params.guildId},{$set:req.body},{new:true});return json(res,p)}catch(e){return json(res,{error:e.message},400)}});
  app.delete('/api/guilds/:guildId/panels/:id',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);await TicketPanel.deleteOne({_id:req.params.id,guildId:req.params.guildId});return json(res,{ok:true})}catch(e){return json(res,{error:e.message},400)}});
  app.post('/api/guilds/:guildId/panels/:id/publish',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);const p=await TicketPanel.findOne({_id:req.params.id,guildId:req.params.guildId});if(!p)return json(res,{error:'Panel not found'},404);const channel=client.channels.cache.get(p.channelId)||await client.channels.fetch(p.channelId).catch(()=>null);if(!channel?.isTextBased())return json(res,{error:'Panel channel not found or is not text based'},400);const {ContainerBuilder,TextDisplayBuilder,SeparatorBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,MessageFlags}=require('discord.js');const typeDocs=await TicketType.find({_id:{$in:p.ticketTypeIds||[]},guildId:req.params.guildId,enabled:true});const styles={Primary:ButtonStyle.Primary,Secondary:ButtonStyle.Secondary,Success:ButtonStyle.Success,Danger:ButtonStyle.Danger};const b=typeDocs.map(t=>new ButtonBuilder().setCustomId(`open:${t.id}`).setLabel(t.buttonLabel||t.name).setStyle(styles[t.buttonStyle]||ButtonStyle.Primary));const rows=[];for(let i=0;i<b.length;i+=5)rows.push(new ActionRowBuilder().addComponents(...b.slice(i,i+5)));const c=new ContainerBuilder().setAccentColor(parseInt((p.color||'#8B5CF6').replace('#',''),16)||0x8B5CF6).addTextDisplayComponents(new TextDisplayBuilder().setContent(`## ${p.title||p.name}`),new TextDisplayBuilder().setContent(p.description||'Select a support option below.')).addSeparatorComponents(new SeparatorBuilder()).addActionRowComponents(...rows);const msg=await channel.send({flags:MessageFlags.IsComponentsV2,components:[c]});p.messageId=msg.id;p.published=true;await p.save();return json(res,{ok:true,messageId:msg.id})}catch(e){return json(res,{error:e.message},400)}});
  app.get('/api/guilds/:guildId/tickets',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);const page=Math.max(1,Number(req.query.page||1)),limit=Math.min(50,Math.max(1,Number(req.query.limit||20)));const filter={guildId:req.params.guildId};if(req.query.status)filter.status=req.query.status;if(req.query.search)filter.$or=[{name:new RegExp(req.query.search,'i')},{ticketId:req.query.search},{creatorTag:new RegExp(req.query.search,'i')},{creatorId:req.query.search}];const [items,total]=await Promise.all([Ticket.find(filter).sort({createdAt:-1}).skip((page-1)*limit).limit(limit).lean(),Ticket.countDocuments(filter)]);return json(res,{items,total,page,limit,pages:Math.ceil(total/limit)})}catch(e){return json(res,{error:e.message},400)}});
  app.get('/api/guilds/:guildId/transcripts',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);const page=Math.max(1,Number(req.query.page||1)),limit=Math.min(50,Math.max(1,Number(req.query.limit||20)));const [items,total]=await Promise.all([Transcript.find({guildId:req.params.guildId}).sort({createdAt:-1}).select('-html').skip((page-1)*limit).limit(limit).lean(),Transcript.countDocuments({guildId:req.params.guildId})]);return json(res,{items,total,page,limit,pages:Math.ceil(total/limit)})}catch(e){return json(res,{error:e.message},400)}});
  app.delete('/api/guilds/:guildId/transcripts/:id',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);await Transcript.deleteOne({_id:req.params.id,guildId:req.params.guildId});return json(res,{ok:true})}catch(e){return json(res,{error:e.message},400)}});
  app.get('/api/guilds/:guildId/logs',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);return json(res,await AuditLog.find({guildId:req.params.guildId}).sort({createdAt:-1}).limit(100).lean())}catch(e){return json(res,{error:e.message},400)}});
  app.get('/api/guilds/:guildId/staff',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);return json(res,await StaffMember.find({guildId:req.params.guildId}).sort({ticketsHandled:-1}).lean())}catch(e){return json(res,{error:e.message},400)}});
  app.get('/api/guilds/:guildId/bot-profile',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);return json(res,await BotProfile.findOneAndUpdate({guildId:req.params.guildId},{$setOnInsert:{guildId:req.params.guildId}},{upsert:true,new:true}))}catch(e){return json(res,{error:e.message},400)}});
  app.put('/api/guilds/:guildId/bot-profile',auth,async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);return json(res,await BotProfile.findOneAndUpdate({guildId:req.params.guildId},{$set:req.body,$setOnInsert:{guildId:req.params.guildId}},{upsert:true,new:true}))}catch(e){return json(res,{error:e.message},400)}});
  app.post('/api/guilds/:guildId/upload',auth,upload.single('file'),async(req,res)=>{try{await ensureGuildAccess(req,req.params.guildId);if(!req.file)return json(res,{error:'Image required'},400);const base64=`data:${req.file.mimetype};base64,${req.file.buffer.toString('base64')}`;return json(res,{url:base64})}catch(e){return json(res,{error:e.message},400)}});
  app.get('/transcript/:publicId',async(req,res)=>{const t=await Transcript.findOne({publicId:req.params.publicId}).lean();if(!t)return res.status(404).send('Transcript not found.');if(t.visibility==='staff' && !req.session.user)return res.status(401).send('This transcript is restricted.');res.type('html').send(t.html)});
  app.get('/dashboard/',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
}
module.exports = { startDashboard };
